<a href="https://colab.research.google.com/github/mrohani/Keyword-Trends-Analyser/blob/main/Keyword_Trend_Analyser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Keyword Trends Analyser

*** برای اجرا این برنامه بعد از تغیر موارد مربوط به قسمت Runtime برید و بر روی گزینه  Run all کلیک کنید

In [5]:
#@title
!pip install pytrends
from pytrends.request import TrendReq
pytrends = TrendReq()
import pandas as pd                       
import time
import datetime
from datetime import datetime, date, time

Requirement already satisfied: pytrends in /usr/local/lib/python3.7/dist-packages (4.7.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pytrends) (4.2.6)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.7/dist-packages (from pytrends) (1.1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pytrends) (2.23.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2.8.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (3.0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25->pytrends) (1.15.0)

#Rising Trends⚡

کلمات مرتبط
کافیه در این قسمت بر روی قسمت ۱۱ دوبار کلیک کنید و کلمات مد نظرتون جایگزین کنید

In [6]:
#@title
kw_list=['موبایل', 'لپ تاپ', 'تبلت','طلا','انتخابات']
pytrends.build_payload(kw_list, timeframe='today 3-m', geo='IR')

In [7]:
#@title
related_queries = pytrends.related_queries()
#related_queries.values()

In [8]:
#@title
related_queries.get('موبایل').get('rising')

                                              query  value
0                  نصب فیلتر شکن روی موبایل سامسونگ  10050
1                               خرید موبایل ای فردا   5250
2               پرداخت بیمه تامین اجتماعی با موبایل   3400
3                                 مرکز موبایل ایران   3300
4                                  ویز مارکت موبایل   1600
5                           دانلود پابجی اصل موبایل   1000
6   چگونه در کالاف دیوتی موبایل اسکین رایگان بگیریم    900
7                     فیلتر شکن قابل نصب روی موبایل    900
8                               دانلود پاپجی موبایل    550
9                                     چت روم موبایل    500
10                     فیلترشکن قابل نصب روی موبایل    300
11                     سیزن جدید کالاف دیوتی موبایل    250
12                                      آوند موبایل    250
13                                      موبایل پوکو    200
14                                     پابچی موبایل    180
15                                       activision    150
16                                       gsm موبایل    150
17                   بهترین تفنگ کالاف دیوتی موبایل    150
18                                       موبایل ۱۴۰    150
19                       دانلود call of duty موبایل    150
20                         آپدیت کالاف دیوتی موبایل    140
21                                   موبایل پوکو x3    130
22                               دانلود فیفا موبایل    120
23                           هولدر موبایل دیجی کالا    120
24                         دانلود بازی پاپجی موبایل    120

#Top Trends(موبایل)

In [9]:
#@title
related_queries.get('موبایل').get('top')

                        query  value
0                       کالاف    100
1                کالاف موبایل     99
2                 کالاف دیوتی     92
3          کالاف دیوتی موبایل     91
4                       پابجی     81
5                 گوشی موبایل     77
6                 بازی موبایل     66
7                 قیمت موبایل     60
8                  زنگ موبایل     36
9              موبایل سامسونگ     32
10           موبایل دیجی کالا     32
11                خرید موبایل     29
12             موبایل شیائومی     21
13               موبایل ایران     20
14           قیمت گوشی موبایل     20
15               بازار موبایل     19
16            آهنگ زنگ موبایل     18
17    بازی کالاف دیوتی موبایل     16
18          دانلود زنگ موبایل     16
19        دانلود کالاف موبایل     16
20        گوشی موبایل سامسونگ     14
21  دانلود کالاف دیوتی موبایل     13
22        گوشی موبایل شیائومی     13
23                مرجع موبایل     12
24                سایت موبایل     11

# Rising Trends(تبلت)

In [10]:
#@title
related_queries.get('تبلت').get('rising')

               query  value
0  تبلت سامسونگ t505   6200
1          تبلت بزرگ     60

# Top Trends(تبلت)

In [11]:
#@title
related_queries.get('تبلت').get('top')

                     query  value
0             تبلت سامسونگ    100
1                قیمت تبلت     76
2                تبلت لنوو     46
3        قیمت تبلت سامسونگ     33
4           تبلت دیجی کالا     21
5                 عکس تبلت     18
6                 قاب تبلت     16
7                خرید تبلت     15
8                تبلت t295     11
9             تبلت شیائومی     10
10              تبلت هواوی     10
11          قیمت تبلت لنوو     10
12              تبلت ایسوس      8
13                تبلت اپل      7
14         تبلت دانش آموزی      7
15       تبلت سامسونگ t295      7
16               تبلت بزرگ      5
17       خرید تبلت سامسونگ      5
18              تبلت نارتب      4
19                کیف تبلت      4
20    قیمت تبلت دانش آموزی      4
21            تبلت ویندوزی      3
22         قیمت تبلت ارزان      3
23            تبلت لنوو m7      3
24  قیمت تبلت سامسونگ t295      2

#Rising Trends(لپ تاپ)

In [12]:
#@title
related_queries.get('لپ تاپ').get('rising')

                       query  value
0         تعمیر لپ تاپ شیراز    350
1          خرید لپ تاپ استوک    110
2  نصب اینستاگرام روی لپ تاپ     70
3                 کیف لپ تاپ     40

#Top Trends(لپ تاپ)

In [13]:
#@title
related_queries.get('لپ تاپ').get('top')

                      query  value
0               قیمت لپ تاپ    100
1              لپ تاپ ایسوس     65
2               لپ تاپ لنوو     51
3               خرید لپ تاپ     33
4          دیجی کالا لپ تاپ     30
5         قیمت لپ تاپ ایسوس     20
6                لپ تاپ اپل     14
7          قیمت لپ تاپ لنوو     12
8             لپ تاپ گیمینگ     11
9        تعمیر لپ تاپ شیراز     11
10             لپ تاپ استوک      9
11              لپ تاپ ایسر      8
12              فروش لپ تاپ      8
13               کیف لپ تاپ      8
14           تعمیرات لپ تاپ      5
15        اسکرین شات لپ تاپ      5
16              مینی لپ تاپ      4
17          قیمت لپ تاپ اپل      4
18      کیبورد فارسی لپ تاپ      3
19        خرید لپ تاپ استوک      3
20             لپ تاپ هواوی      3
21              لپ تاپ قسطی      3
22         لب تاب یا لپ تاپ      2
23  تعمیر لپ تاپ لنوو شیراز      2
24       خرید لپ تاپ گیمینگ      2

In [14]:
#@title
related_queries.get('طلا').get('rising')

                            query  value
0       قیمت طلا ۱۵ اردیبهشت ۱۴۰۰   8150
1       قیمت طلا ۱۸ اردیبهشت ۱۴۰۰   6950
2       قیمت طلا ۲۵ اردیبهشت ۱۴۰۰   6850
3       قیمت طلا ۱۲ اردیبهشت ۱۴۰۰   6050
4       قیمت طلا ۲۰ اردیبهشت ۱۴۰۰   4750
5       قیمت طلا ۱۹ اردیبهشت ۱۴۰۰   4600
6       قیمت طلا ۲۸ اردیبهشت ۱۴۰۰   4600
7        قیمت طلا ۴ اردیبهشت ۱۴۰۰   4250
8            قیمت طلا ۱۶ اسفند ۹۹   4200
9       قیمت طلا ۱۷ اردیبهشت ۱۴۰۰   3800
10      قیمت طلا ۱۶ اردیبهشت ۱۴۰۰   3600
11      قیمت طلا ۲۳ اردیبهشت ۱۴۰۰   3300
12       قیمت طلا ۶ اردیبهشت ۱۴۰۰   2600
13      قیمت طلا ۳۰ اردیبهشت ۱۴۰۰   2550
14      قیمت طلا ۲۶ اردیبهشت ۱۴۰۰   2050
15       قیمت طلا ۵ اردیبهشت ۱۴۰۰   2050
16       قیمت طلا ۱۴ فروردین ۱۴۰۰   2000
17       قیمت طلا ۲۱ فروردین ۱۴۰۰   1550
18         قيمت طلا ١٨ عيار امروز    650
19              قيمت طلا ١٨ امروز    400
20         تعبیر خواب گوشواره طلا    300
21                      .قیمت طلا    200
22  پیش بینی قیمت طلا در سال 1400    200
23                   نرخ طلا وارز    140
24          تعبیر خواب دزدیدن طلا    130

In [15]:
#@title
related_queries.get('طلا').get('top')

                   query  value
0               طلا قیمت    100
1              طلا امروز     20
2         قیمت امروز طلا     15
3                طلا روز     11
4           قیمت طلا روز     10
5                سکه طلا      8
6                نرخ طلا      7
7           قیمت سکه طلا      6
8            طلا لحظه ای      5
9          قیمت لحظه طلا      5
10      قیمت طلا لحظه ای      5
11            طلا آنلاین      5
12             سکه و طلا      5
13               ارز طلا      4
14        قیمت طلا و سکه      4
15  قیمت آنلاین قیمت طلا      4
16       قیمت طلا آنلاین      4
17               جیب طلا      3
18         طلا ایران جیب      3
19              طلا گرمی      3
20            طلا انلاین      3
21               گرم طلا      3
22              سایت طلا      3
23           قیمت طلا ۱۸      3
24            قیمت خودرو      3

In [16]:
#@title
related_queries.get('انتخابات').get('rising')

                                                query  value
0                             اینترنت رایگان انتخابات  82450
1           جدیدترین اخبار انتخابات ریاست جمهوری 1400  52500
2                               قانون انتخابات شوراها  36200
3                                 تاريخ انتخابات ١٤٠٠  31650
4                        سخنان رهبری در مورد انتخابات  26200
5                                انتخابات ۱۴۰۰ کی است  25750
6                   آخرین اخبار انتخابات ریاست جمهوری  21250
7                   پخش زنده انتخابات فدراسیون فوتبال  20450
8                           ictgifts ir هدیه انتخابات  20350
9                                        انتخابات کیه  15950
10                     نتیجه انتخابات فدراسیون فوتبال  14550
11                          انتخابات ۱۴۰۰ چه روزی است  10650
12                          اخرین اخبار انتخابات 1400  10550
13                      ماده 32 قانون انتخابات شوراها  10500
14                          آخرین اخبار انتخابات 1400  10500
15  چه کسانی در انتخابات ریاست جمهوری ۱۴۰۰ شرکت میکند   5150
16                     نتایج انتخابات فدراسیون فوتبال   4900
17                                اخبار انتخابات 1400   1950
18                                تاریخ انتخابات ۱۴۰۰   1300
19                                 ستاد انتخابات کشور   1250
20                              نظرسنجی انتخابات 1400    900
21                                         وزارت کشور    900
22                                              رئیسی    900
23                                      ستاد انتخابات    800
24                            انتخابات شورای شهر ۱۴۰۰    550

In [17]:
#@title
related_queries.get('انتخابات').get('top')

                            query  value
0           انتخابات ریاست جمهوری    100
1                   انتخابات ۱۴۰۰     93
2                   انتخابات 1400     57
3                  تاریخ انتخابات     30
4              انتخابات شورای شهر     28
5      انتخابات ریاست جمهوری ۱۴۰۰     27
6                  اخبار انتخابات     25
7                      احمدی نژاد     23
8      انتخابات ریاست جمهوری 1400     23
9     انتخابات ریاست جمهوری ایران     22
10                  زمان انتخابات     21
11    تاریخ انتخابات ریاست جمهوری     14
12                          رئیسی     14
13  ثبت نام انتخابات ریاست جمهوری     13
14            تاریخ انتخابات ۱۴۰۰     13
15                 رئیسی انتخابات     13
16     زمان انتخابات ریاست جمهوری     11
17               نظرسنجی انتخابات     10
18            اخبار انتخابات 1400     10
19                  ستاد انتخابات      9
20    اخبار انتخابات ریاست جمهوری      9
21          کاندیدای ریاست جمهوری      9
22            اخبار انتخابات ۱۴۰۰      6
23             ستاد انتخابات کشور      6
24         نامزدهای انتخابات ۱۴۰۰      6